version: '1.0.{build}'

clone_folder: c:\oavb
clone_depth: 20

environment:
  # Config for mrp Windows build
  WPCAP_DIR: c:\oavb\WpdPack
  
install:
  - git submodule update --init --recursive
  # download WinPcap developer module and unzip it
  - ps: Start-FileDownload 'https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip'
  - ps: 7z x WpdPack_4_1_2.zip

before_build:
  # cmake
  - choco upgrade cmake
  - set path=C:\Program Files\CMake\bin;%path%

build_script:
  - cd c:\oavb
  - cmake CMakeLists.txt -G "Visual Studio 12 2013"
  - cmake --build . --config Release
